config/routes.rb
Bookshare::Application.routes.draw do

  root 'pages#index'

  resources :books, param: :isbn do
    member do
      post   'claim'
      delete 'claim' => 'books#unclaim'
    end

    collection do
      get 'search'
      get 'category/:id' => 'books#category'
      get 'categories'
    end
  end

  resources :orders do
    collection do
      post 'shipping'
      get  'payment'
    end
  end

  namespace :admin do
    resources :sessions
    resources :orders do
      member do
        get 'prepare'
        get 'buy'
      end
    end
  end

  get '/faq' => 'pages#faq'
  get '/how' => 'pages#how'

end

app/models/order.rb
class Order < ActiveRecord::Base
  include ActiveModel::Transitions

  has_many :items
  has_many :books, through: :items

  before_save :make_uuid


  def make_uuid
    self.uuid = SecureRandom.hex(16)
  end

  validates_uniqueness_of :email, case_sensitive: false, allow_nil: true
  validates_presence_of :name,     allow_nil: true
  validates_presence_of :address1, allow_nil: true
  validates_presence_of :city,     allow_nil: true
  validates_presence_of :state,    allow_nil: true
  validates_presence_of :zip,      allow_nil: true
  validates_presence_of :country,  allow_nil: true

  state_machine attribute_name: :status do
    state :pending_info
    state :pending_payment
    state :paid
    state :shipped
    state :duplicate

    event :shipment_manifest do
      transitions to: :pending_payment, from: [:pending_info, :pending_payment]
    end

    event :paid do
      transitions to: :paid, from: [:pending_payment]
    end

    event :duplicate do
      transitions to: :duplicate, from: [:pending_info, :pending_payment]
    end

    event :ship do
      transitions to: :shipped, from: [:paid]
    end

  end

  def reserve_books
    self.books.each do |book|
      book.reserve!
    end
  end

  def unreserve_books
    self.books.each do |book|
      book.unreserve!
    end
  end

  def shipment(weight, box="MediumFlatRateBox")

    to_address = EasyPost::Address.create(
      :name => self.name,
      :street1 => self.address1,
      :street2 => self.address2,
      :city => self.city,
      :state => self.state,
      :zip => self.zip
    )

    # TODO Pull this from a config
    from_address = EasyPost::Address.create(
      :company => 'Steve Corona',
      :street1 => '',
      :city => '',
      :state => '',
      :zip => '',
    )

    parcel = EasyPost::Parcel.create(
      :predefined_package => box,
      :weight => weight
    )

    shipment = EasyPost::Shipment.create(
      :to_address => to_address,
      :from_address => from_address,
      :parcel => parcel,
    )

    shipment

  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController
  def index
    @orders = Order.where("status = ?", :paid).order("updated_at")
  end

  def prepare
    @order = Order.find(params[:id])

    if params[:box] && params[:weight]
      @shipment = @order.shipment(params[:weight], params[:box])
      @shipment.rates.each do |rate|
        if rate.service == "Priority"
          @rate = rate
        end
      end
    end
  end

  def buy
    @order = Order.find(params[:id])

    if params[:box] && params[:weight]
      @shipment = @order.shipment(params[:weight], params[:box])
    end

    @shipment.rates.each do |rate|
      if rate.service == "Priority"
        @rate = rate
      end
    end

    @shipment.buy(
      :rate => @rate
    )

    @order.ship!

  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
    redirect_to order_path(@order.uuid) if @order.duplicate?
  end

  def shipping
    @order.name     = params[:order][:name]
    @order.address1 = params[:order][:address1]
    @order.address2 = params[:order][:address2]
    @order.city     = params[:order][:city]
    @order.state    = params[:order][:state]
    @order.zip      = params[:order][:zip]
    @order.country  = "United States of America" # Force country for now

    # TODO: Handle error case
    if @order.save
      @order.shipment_manifest!
      redirect_to payment_orders_path
    else
      render :new
    end
  end

  def payment
    @shipment = HandlingCalculator.new(@order)
    @shipment.calculate

    @books = @order.books
  end

  def create

    # Prevent duplicate submission
    return redirect_to order_path(@order.uuid) if @order.paid?

    @order.email = params[:email]
    @order.token = params[:token]

    @shipment = HandlingCalculator.new(@order)
    @shipment.donate(300) if params[:donation]
    @shipment.calculate

    @order.total_amount    = @shipment.total
    @order.donation_amount = @shipment.donation_rate

    if @order.save
      @payment = Payment.new(@order)
      @payment.charge

      @order.paid!

      @snagged = []

      @order.items.each do |item|
        begin
          item.book.reserve!
          item.status = "reserved"
          item.save
        rescue Exception
          item.status = "snagged"
          item.save
        end
      end

      OrderMailer.thank_you_email(@order).deliver

      cookies[:order] = {
        value: @order.id,
        expires: 1.year.from_now
      }
    else
      @order.email += "DUPLICATE"
      @order.duplicate!
    end

    redirect_to order_path(@order.uuid)

  rescue Stripe::CardError => e
    @order.unreserve_books
  end

  def show
    @order = Order.find_by_uuid(params[:id])

    render :duplicate if @order.duplicate?
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/duplicate.html.slim
.container
  .row
    h2 Uh oh! It looks like you ordered more than once!
    hr
    .col-md-10
      p.lead Sorry about that, but in order to give everyone a fair shot at getting some books, there is a limit of 5 books per person.
      p.lead If you think this was a mistake, hit the contact button above and I'll see what went wrong.
      p.lead P.S Your credit card <b>was not charged</b>.

app/views/orders/new.html.slim
.container
  h2 Shipping Information
  .row
    .col-md-6
      p.lead I'm shipping your books using USPS Media Mail
      p This makes it super cheap to ship you the books, but I need to know your address so I can calculate the costs.

      - if @order.errors.any?
        .alert.alert-danger
          - @order.errors.full_messages.each do |msg|
            p =msg

      = form_tag "/orders/shipping", class: "form-horizontal" do |f|
        .form-group
          label.control-label.col-sm-3 for="order[name]" Name:
          .col-sm-6
            input.form-control name="order[name]" type="text" placeholder="Enter your Name"
        .form-group
          label.control-label.col-sm-3 for="order[address1]" Address Line 1:
          .col-sm-8
            input.form-control name="order[address1]" type="text" placeholder="Enter your Address"
        .form-group
          label.control-label.col-sm-3 for="order[address2]" Address Line 2:
          .col-sm-8
            input.form-control name="order[address2]" type="text" placeholder="Enter your Address (optional)"
        .form-group
          label.control-label.col-sm-3 for="order[city]" City:
          .col-sm-6
            input.form-control name="order[city]" type="text" placeholder="Enter your City"
        .form-group
          label.control-label.col-sm-3 name="order[state]" for="name" State/Region:
          .col-sm-6
            input.form-control name="order[state]" type="text" placeholder="Enter your State"
        .form-group
          label.control-label.col-sm-3 for="order[zip]" Zip/Postal Code:
          .col-sm-6
            input.form-control name="order[zip]" type="text" placeholder="Enter your Zip Code"
        .form-group
          label.control-label.col-sm-3 for="order[country]" Country:
          .col-sm-6
            p US Only (Sorry! I'm still figuring out International Shipping!)
        button.btn.btn-primary type="submit" Calculate Shipping
        //p.lead Sorry about that, orders are wonky at the moment.
    .col-md-6
      p.lead I'm going to send you these books

      table.table.table-striped

        thead
          tr
            th ISBN
            th Title
        tbody
          - @order.books.each do |book|
            tr
              td =book.isbn
              td =book.title

app/views/orders/payment.html.slim
.container
  h2 Pay for shipping, get books
  .row
    .col-md-6
      .row
        .col-md-8
          p.lead Breakdown of Costs

          table.table.table-striped
            thead
              tr
                th Description
                th Cost

            tbody
              tr
                td USPS Media Mail (Flat-Rate)
                td =number_to_currency(@shipment.shipping_rate/100.0)
              tr
                td Stripe Payment Processing Fee
                td =number_to_currency(@shipment.gateway_rate/100.0)
              tr
                td 6x6x6 Box + Packing Tape
                td =number_to_currency(@shipment.packing_rate/100.0)
              tr
                td Optional Donation
                td#donation_amount =number_to_currency(@shipment.donation_rate/100.0)
            tfoot
              tr
                td
                  b Total Cost
                td#total_amount data-amount=@shipment.total
                  b =number_to_currency(@shipment.total/100.0)
      .row
        .col-md-12
          =form_tag orders_path, id: "payment"
            input#token  name="token"  type="hidden" value=""
            input#email  name="email"  type="hidden" value=""
            label.checkbox-inline
              input name="donation" type="checkbox" id="donation" value="yes"
                b Optional
                |: Include <b>$3</b> donation to help cover hosting/packing costs?
                span.help-block Helps with the costs for Heroku, CloudFlare, Domain, and RubyMotion.
          hr
          h4
            | Total Charge:&nbsp;
            span#total_charge =number_to_currency(@shipment.total/100.0)

          button.btn.btn-primary.btn-lg#checkout Pay for Shipping

    .col-md-6
      .row
        .col-md-12
          p.lead I'm going to send you these books

          table.table.table-striped

            thead
              tr
                th ISBN
                th Title
            tbody
              - @books.each do |book|
                tr
                  td =book.isbn
                  td =book.title

      .row
        .col-md-12
          p.lead To this address
          p
            | <b>#{@order.name}</b> <br>
            | #{@order.address1} <br>
            - unless @order.address2.blank?
              | #{@order.address2} <br>
            | #{@order.city}, #{@order.state} #{@order.zip}<br>
            | #{@order.country}

app/views/orders/show.html.slim
.container
  h2 Thanks for your order!

  p.lead It will take 1-3 weeks for your books to arrive.

  hr

  - if @order.items.where("status = ?", :snagged).count > 0
    .alert.alert-warning
      p One of your items was snagged from you! That means someone else paid for shipping for one of the same books while you were checking out. I'll still send the rest of your books and will try send an extra (random) one!

  .row
    .col-md-6
      p.lead I'm going to send you these books

      table.table.table-striped

        thead
          tr
            th ISBN
            th Title
            th
        tbody
          - @order.items.each do |item|
            tr
              td =item.book.isbn
              td =item.book.title
              td =item.status
    .col-md-3
      p.lead To this address

      p
        | <b>#{@order.name}</b> <br>
        | #{@order.address1} <br>
        - unless @order.address2.blank?
          | #{@order.address2} <br>
        | #{@order.city}, #{@order.state} #{@order.zip}<br>
        | #{@order.country}
    .col-md-3
      p.lead Payment
      p
        | Cost for Shipping:&nbsp;
        =number_to_currency((@order.total_amount-@order.donation_amount)/100.0)
      p
        | Donation:&nbsp;
        =number_to_currency(@order.donation_amount/100.0)