config/routes.rb
Bookshare::Application.routes.draw do

  root 'pages#index'

  resources :books, param: :isbn do
    member do
      post   'claim'
      delete 'claim' => 'books#unclaim'
    end

    collection do
      get 'search'
      get 'category/:id' => 'books#category'
      get 'categories'
    end
  end

  resources :orders do
    collection do
      post 'shipping'
      get  'payment'
    end
  end

  namespace :admin do
    resources :sessions
    resources :orders do
      member do
        get 'prepare'
        get 'buy'
      end
    end
  end

  get '/faq' => 'pages#faq'
  get '/how' => 'pages#how'

end

app/models/book.rb
class Book < ActiveRecord::Base
  include ActiveModel::Transitions
  belongs_to :category

  state_machine attribute_name: :status do
    state :avaliable
    state :reserved

    event :reserve do
      transitions to: :reserved, from: [:avaliable]
    end

    event :unreserve do
      transitions to: :avaliable, from: [:reserved]
    end
  end

  def self.text_search(query)

    if query.present?
      rank = <<-RANK
        ts_rank(to_tsvector(title), plainto_tsquery(#{sanitize(query)})) +
        ts_rank(to_tsvector(description), plainto_tsquery(#{sanitize(query)}))
      RANK
      where("title @@ :q or description @@ :q", q: query).order("#{rank} desc")
    else
      scoped
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  BOOKS_PER_PAGE=32

  respond_to :html, :json
  protect_from_forgery except: [:create]

  def index
    @books = Book.order("status, (ratings_count * average_rating) desc").page(params[:page]).per_page(BOOKS_PER_PAGE)
  end

  def category
    @category = Category.find(params[:id])
    @books    = @category.books.where(status: :avaliable).page(params[:page]).per_page(BOOKS_PER_PAGE)
    render :index
  end

  def categories
    @categories = Category.joins("JOIN books ON books.category_id = categories.id").where("books.status = 'avaliable'").group("categories.id")
  end

  def show
    @book = Book.find_by_isbn!(params[:isbn])
  end

  def create

    # TODO: Move token auth to a helper
    if params[:token].nil? || params[:token] != ENV['SECRET_TOKEN']
      return render status: 401, nothing: true
    end

    loader = BookLoader.new(params[:isbn], cover: :amazon, data: :google)
    loader.publish

    respond_with loader.book
  end

  def claim
    @book = Book.find_by_isbn!(params[:isbn])
    @item = Item.new(book_isbn: @book.isbn, order_id: @order.id)
    @item.save
    redirect_to book_path(@book.isbn)
  end

  def unclaim
    @item = @order.items.where(book_isbn: params[:isbn]).first
    @item.delete
    redirect_to book_path(params[:isbn])
  end

  def search
    @books = Book.text_search(params[:query])
  end

end

app/helpers/books_helper.rb
module BooksHelper

  BOOK_LIMIT = 5

  def amazon_link(book, opts={})
    link_to "View on Amazon", "https://www.amazon.com/gp/product/#{book.isbn}", opts
  end

  def book_cover_image(book, opts={})
    opts[:width]   ||= 201
    opts[:height]  ||= 300
    opts[:crop]    ||= "fill"
    opts[:gravity] ||= "north"

    cl_image_tag("#{book.isbn}_cover.jpg", opts)
  end

  def books_left
    BOOK_LIMIT - @order.items.count
  end
end

app/views/books/categories.html.slim
.container
  h1 Genres

  ul
    - @categories.each do |category|
      li
        a href="/books/category/#{category.id}" =category.name

app/views/books/index.html.slim
.container
  .row
    .col-md-12
      h1 All of my books

  - if @category
    ol.breadcrumb
      li
        a href=books_path Book Index
      li Category: #{@category.name}

  .row#books
    - @books.each do |book|
      .col-md-3.col-sm-4
        .book
          a href=book_url(book.isbn)
            - if book.avaliable?
              =book_cover_image(book, class: @selected.include?(book.isbn) ? "cover selected" : "cover")
            - else
              =book_cover_image(book, class: "cover reserved")
              span.reserved_overlay TAKEN
  .row
    .col-md-12
      =will_paginate @collection, renderer: BootstrapPagination::Rails

app/views/books/search.html.slim
.container
  .row
    .col-md-6
      ol.breadcrumb
        li
          a href=books_path Book Index
        li Search: "<b>#{params[:query]}</b>"

  - @books.each do |book|
    .media.col-md-8
      a.pull-left href=book_url(book.isbn)
        =book_cover_image(book, width: 75, height: 110, class: "media-object")
      .media-body
        a href=book_url(book.isbn)
          h4.media-heading =book.title
        =truncate(book.description, length: 400)

app/views/books/show.html.slim
.container
  .row
    .col-md-12
      .media
        a.pull-left.hidden-xs
          =book_cover_image(@book, width: 200, height: 300, class: "media-object")
        .media-body
          h4.media-heading=@book.title
          p By #{@book.author}, #{@book.pages} Pages (#{@book.published_year})
          a href="/books/category/#{@book.category.id}" #{@book.category.name}
          hr
          .col-md-8
            - unless @book.notes.nil?
              h5 Notes from Steve
              p =@book.notes

            .hidden-sm.hidden-xs
              h5 Book Description
              p =@book.description
          .col-md-4
            - if @order.paid?
              p You've already placed your order! Thanks!
            - elsif @order.items.where(book_isbn: @book.isbn).count == 1
              p
                | You claimed this book! You can choose up to
                =" #{books_left}"
                |  more books!
                =link_to " (Unclaim)", claim_book_path(@book.isbn), method: :delete
              p
                b You can lose this book if someone else pays for shipping first!
            - elsif books_left <= 0
              p You've claimed the maximum of 5 books.
            - elsif @book.avaliable?
              =link_to "Claim this book!", claim_book_path(@book.isbn), method: :post, class: "btn btn-primary btn-lg btn-block"
            br
            =amazon_link(@book, class: "btn btn-lg btn-default btn-block", target: "_new")

  hr
  - if @book.category.name == "Computers"
    .row
      .col-md-12
/!        h3 Hey! Did you know I wrote a book on PHP?
/!        img#scalingphp.pull-left src="https://s3.amazonaws.com/gumroad/files/9612823a1969f0d130b06daba187ce3f/original/Screen_20Shot_202013-02-26_20at_209.05.56_20PM.png"
        p.lead
/!          | I wrote a really badass book called <a href="http://scalingphpbook.com">Scaling PHP Applications.</a> It's 218 pages of
/!          |  the most awesome, hard-to-find content on my experiences Scaling PHP to 30 million users at Twitpic. <a href="http://scalingphpbook.com">Check it out!</a>
        p
/!          | (Sorry for the shameless plug, but I saw that you were looking at computer books.)